import os
from time import sleep
def agent():
    print("You have selected the character Agent Smith. \n")
    sleep(1)
    print("")
    print("** Agent Smith is at The Lafayette Hotel searching for Morpheus and his crew **")
    sleep(2)
    print("")
    print("** Agent Smith hears something on his earpiece and pauses **")
    sleep(2)
    print("")
    print("He listens to the earpiece and tells the other agents that they are on the eighth floor")
    sleep(.5)
    print("")
    print("** A cop stops by a room and examines it and hears a cough through the walls**")
    sleep(1)
    print("")
    print("Agent Smith morphs into the policeman's body and takes over")
    print("")
    sleep(1)
    print("Agent Smith sticks his hands in the wall and grabs Neo. Morpheus sees and jumps through the wall and tackles the agent")
    sleep(1)
    print("")
    print("They both take turns throwing punches")
    sleep(1)
    fighting()
    print("Agent Smith slams Morpheus into the wall")
    print("")
    sleep(1)
    print("Morpheus gets back up and they continue fighting")
    print("")
    sleep(1)
    fighting()
    print("")
    print("Agent Smith kicks Morpheus and he hits his head on the toilet")
    print("")
    sleep(1)
    toilet()
    sleep(1)
    print("Morpheus and Agent Smith continue fighting")
    print("")
    print("")
    fighting()
    sleep(1)
    print("")
    print("Agent Smith punches Morpheus into the air")
    print("")
    sleep(1)
    fist()
    print("Agent Smith walks away and tells the agents to take him")
    
def fist():
    print("                __________                  __,___/  ',',")
    print("         ___.--'          '\'.         ____/  l   \    ','-,")
    print("  ------f''               // \\\       \  (l\ \    \     \ \',")
    print("        |                    |||       /   u       |      \ \ |")
    print("        |                    |||     _ )          /       | |  |")
    print("    ----L_-XXX-.             .|'    / U          <        | |  |")
    print("                '\   -<_____///     \           6 )       | |  |")
    print("                  \___)     -'       '.       -.<'       / /   |")
    print("                                      |'.___  |       _._.'   /")
    print("                                      |     ./     _.'.'   _.'")
    print("                                     /      |'----'     _.'")

def fighting():
    print("   o   o")
    print("   k8 83,")
    print("  /\   /|")

def toilet():
    print("                  \     \.")
    print("                  |'\_____|")
    print("                  |` |    |")
    print("                  |  |    | ")
    print("     __-====-__  _|  |    |")
    print("    (~<       >~>  \ |    |")
    print("    !~~-====-~~/----`+----/")
    print("     \         \___     / ")
    print("      >------\     \  <  ")
    print("     <_________________>")

def main():
    agent()

main()
